version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: emanaleads-postgres
    environment:
      POSTGRES_DB: emanaleads
      POSTGRES_USER: emanaleads
      POSTGRES_PASSWORD: emanaleads123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data: